apiVersion: v1
kind: Service
metadata:
  name: {{ template "dex.name" . }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  selector:
    app: {{ template "dex.name" . }}
  ports:
  - name: http
    port: 80
    targetPort: 5556

